### ISSUE TITLE
TRV: Need more consistent MQTT messages

### ISSUE THREAD

**Issue by Ysbrand** [btsimonh/Tasmota#4]
At the moment it's pretty tough to parse MQTT messages as they do not contain a single shared field.

Topic:
`stat/ESP32-1/EQ3/001A2216A458`

A regular parse able json
```
{
"trv":"00:1a:22:16:a4:58",
"blestate":"DONENOTIFIED",
"raw":"020108040428000000001803231607",
"temp":20.0,
"posn":4,
"mode":"auto",
"boost":"inactive",
"dst":"set",
"window":"closed",
"state":"unlocked",
"battery":"GOOD",
"holidayend":"00-00-00 00:00"
}
```

```
{
"trv":"00:1a:22:16:3f:0a",
"blestate":"DONENOTIFIED",
"raw":"21010A212630166626840A9022902290",
"profileday1":"5.0-05:30,19.0-08:00,11.0-17:00,19.0-22:00,5.0-24:00,17.0-24:00,17.0-24:00"
}
```

And the one causing problems
```
{
"result":"queued"
}
```

Suggest to have something like:
```
{
"trv":"00:1a:22:16:a4:58",
"blestate":"queued",
}
```
In other words, every message has at least the mac address and a status field.

Background:
While I'm trying to check for the contents of a field in HA, it causes error messages and filling up the logs. SO I can still get things to work but not in a clean way. Might be my lack of knowledge on HA.

(And I think the same applies to the tele/.../BLE messages)

**Comment by btsimonh** [comment]
still under review...  posting to keep active

**Comment by btsimonh** [comment]
- platform: mqtt
  name: werkkamer_radiator_climate
  modes:
    - "auto"
    - "off"
    - "heat"
  min_temp: 4.5
  max_temp: 23.0
  temp_step: 0.5
  mode_command_topic: cmnd/ESP32-1/EQ3/001A2216A458/mode
  temperature_command_topic: cmnd/ESP32-1/EQ3/001A2216A458/settemp
  current_temperature_topic: tele/ESP32-1/SENSOR
  current_temperature_template: >
    {% if value_json["ATC0137cb"] is defined %}
      {{ value_json["ATC0137cb"]["Temperature"] }}
    {% endif %}
  temperature_state_topic: stat/ESP32-1/EQ3/001A2216A458
  # temperature_state_template: '{{ value_json.temp }}'
  temperature_state_template: >
    {% if value_json.result != "queued" %}
      {{ value_json.temp }}
    {% else %}
      {{ state_attr('climate.werkkamer_radiator_climate','temperature') }}
    {% endif %}
  mode_state_topic: stat/ESP32-1/EQ3/001A2216A458
  mode_state_template: >
    {% if value_json.mode == "auto" %}
    auto  
    {% elif value_json.temp == "4.5" %}
    'off'
    {% elif value_json.valve > "5" %}
    heat
    {% endif %}
  precision: 0.5

**Comment by btsimonh** [comment]
Test Discovery messages:

adds an attr entity as a sensor
```
{
"topic":"homeassistant/sensor/EQ3001A22092CDB/attr/config",
"payload":"{"device":{"name":"EQ3001A22092CDB","identifiers":["001A22092CDB"],"mf":"EQ3","mdl":"EQ3"},"unique_id":"001A22092CDBattr","state_topic":"stat/EQ3/001A22092CDB","name":"EQ3001A22092CDB_attr","value_template":"{{ value_json.mode }}","json_attributes_topic":"stat/EQ3/001A22092CDB"}"
}
```

adds the climate entity with presets and 'hvac action' (off/heating):
```
{
"topic":"homeassistant/climate/EQ3001A22092CDB/control/config",
"payload":"{"device":{"name":"EQ3001A22092CDB","identifiers":["001A22092CDB"],"mf":"EQ3","mdl":"EQ3"},"name":"EQ3001A22092CDB","max_temp":30,"min_temp":5,"temperature_command_topic":"cmnd/tasmota_E89E98/EQ3/001A22092CDB/settemp","mode_command_topic":"cmnd/tasmota_E89E98/EQ3/001A22092CDB/mode","modes":["off","heat","auto","idle"],"temperature_unit":"c","temp_step":"0.5","precision":0.5,"unique_id":"001A22092CDB","action_topic":"stat/EQ3/001A22092CDB","action_template":"{{ 'off' if value_json.posn < 25 else 'heating' }}","hold_command_topic":"cmnd/tasmota_E89E98/EQ3/001A22092CDB","hold_state_template":"{{ value_json.mode }}","hold_state_topic":"stat/EQ3/001A22092CDB","hold_modes":["auto","manual","off","on","boost","unboost","lock","unlock","day","night","reqprofile 0"],"current_temperature_topic":"tele/tasmota_ble/ATC214e0d","current_temperature_template":"{{ value_json.Temperature }}","temperature_state_topic":"stat/EQ3/001A22092CDB","temperature_state_template":"{{ value_json.temp }}","mode_state_topic":"stat/EQ3/001A22092CDB","mode_state_template":"{{ value_json.hassmode }}"}"
}
```

**Comment by fightforlife** [comment]
@btsimonh Hi Simon, how do I activate the test HA Discovery Messages on the latest EQ3 branch?

**Comment by btsimonh** [comment]
ahh..  we've not quite got there yet.
I have a node-red flow which detects EQ3 mqtt messages, and then periodically sends HA discovery messages.
@Ysbrand configured his manually for the moment.
The HUGE step forward we've made is in HA itself in lovelace.
If you are not already using the 'decluttering' card - look it up - @Ysbrand was using the mini-climate card, but configuration of it is complex (a page of yaml per EQ3), but with the decluttering card, you do that once, and then each eq3 is 3-4 lines :)

p.s. make sure you update to a recent push - we found and fixed an issue which was causing eq3 polling to stall (thanks ysbrand for all your help!).

If you want the NR flow, i'll post it here; but my pi was not active this morning and seems non boot - I thought HA on an rpi4 with SSD was going to solve all the instability issues of my rpi3+SD, but maybe not :(.  So when it's back up and I can lift the flow.... 

p.p.s you can send the above manually?  But you may need to use the Alias rather than the mac with latest EQ3 branch.

**Comment by btsimonh** [comment]
damn.  it did not go down - it changed IP! (router reboot)  lucky it's not my primary HA for the moment.

**Comment by Ysbrand** [comment]
To get you going, it's not perfect yet, but pretty useable

disable BLE in the main HAS BLE configuration and save (we're enabling BLE in the autoexec.bat otherwise you might get unwanted reports before we're finished setting up the aliases.

I'm using aliases, you can set them up in an autoexec.bat (new 93.1 TAS feature).

```
BLEAlias 001A2216A458=EQ3werkkamer
BLEAddrFilter 0
MI32Option6 1

bleenableunsaved 1
```

Climate configuration:
```
- platform: mqtt
  name: werkkamer_radiator_climate
  modes: ['off',heat,auto,idle]
  min_temp: 4.5
  max_temp: 23.0
  temp_step: 0.5
  mode_command_topic: cmnd/eq3_devices/EQ3/EQ3werkkamer/mode
  temperature_command_topic: cmnd/eq3_devices/EQ3/EQ3werkkamer/settemp
  current_temperature_topic: tele/tasmota_ble/ATC0137cb
  current_temperature_template: '{{ value_json.Temperature }}'
  temperature_state_topic: stat/EQ3/EQ3werkkamer
  temperature_state_template: '{{ value_json.temp }}'
  mode_state_topic: stat/EQ3/EQ3werkkamer
  mode_state_template: '{{ value_json.hassmode }}'
  hold_command_topic: cmnd/eq3_devices/EQ3/werkkamer
  hold_state_template: '{{ value_json.mode }}'
  hold_state_topic: stat/EQ3/werkkamer
  hold_modes: ["auto","manual","off","on","boost","lock","unlock","day","night"]
  precision: 0.5
```
the tele/tasmota_ble/ATC0137cb is used for the actual room temperature as it is not reported by the EQ3

sensors:
```
- platform: mqtt
  name: "werkkamer_valve"
  state_topic: stat/EQ3/EQ3werkkamer
  value_template: >
    {% if value_json.result == "ok" %}
      {{ value_json.posn }}
    {% else %}
      {{ states('sensor.werkkamer_valve') }}
    {% endif %}
  unit_of_measurement: "%"
```
And if you want to use the decluttering template with the mini climate card (very nice if you need to configure multiple trv's in lovelace):
```
  template_heating:
    card:
      type: 'custom:mini-climate'
      entity: 'climate.[[trv_name]]_radiator_climate'
      name: '[[nice_name]]'
      icon: 'mdi:radiator'
      secondary_info: hvac-mode
      tap_action:
        action: more-info
        entity: 'sensor.[[trv_name]]_valve'
      hvac_mode:
        style: '(value, entity) => ({ color: "black" })'
        source:
          'off':
            icon: 'mdi:power'
            name: 'off'
          idle:
            icon: 'mdi:fan'
            name: idle
          heating:
            icon: 'mdi:weather-sunny'
            name: heat
          auto:
            icon: 'mdi:clock-outline'
            name: auto
      temperature:
        unit: °C
        fixed: 1
        source:
          entity: 'sensor.[[sensor_name]]_temperature'
      fan_mode:
        hide: 'off'
        icon: 'mdi:fan'
        order: 0
        state:
          attribute: preset_mode
        active: '(state, entity) => true'
        source:
          state: state
          auto: auto
          manual: manual
          'off': 'off'
          'on': 'on'
          Boost: boost
          unboost: unboost
          lock: lock
          unlock: unlock
          day: day
          night: night
        change_action: >
          (selected, state, entity) => this.call_service('climate',
          'set_preset_mode', { entity_id: entity.entity_id, preset_mode:
          selected })
      # Hide 3 dots menu
      # fan_mode:
        # hide: on
      indicators:
        valve:
          icon:
            template: '() => "mdi:valve"'
            style: >
              (value) => (value > 80 ? { color: 'red'} 
                : value > 40 ? { color: 'orange'}
                : value > 0 ? { color: 'yellow'}
                : { color: 'green' })
          unit: '%'
          round: 1
          source:
            entity: 'sensor.[[trv_name]]_valve'
        humidity:
          icon:
            template: '() => "mdi:water"'
            style: >
              (value) => (value > 80 ? { color: 'darkblue'} 
                : value > 50 ? { color: 'blue'}
                : value > 40 ? { color: 'lightblue'}
                : { color: 'grey' })
          unit: '%'
          round: 0
          source:
            entity: 'sensor.[[sensor_name]]_humidity'

```
and the lovelace code:
```
    - type: custom:decluttering-card
      template: template_heating
      variables:
        - trv_name: werkkamer
        - nice_name: Werkkamer
        - sensor_name: atc_werkkamer
```
