### ISSUE TITLE
Tasmota EQ3 with Homeassistant

### ISSUE THREAD

**Issue by btsimonh** [btsimonh/Tasmota#6]
The next comment will contain my Node-Red node for making Homeassistant discovery messages

**Comment by btsimonh** [comment]
```
//let scanner = flow.get('scanner');
//let templates = global.get('tasmotatemplates');

//if (!scanner) return;


//msg.payload = scanner;
let eq3s = flow.get('eq3s') || {};
flow.set('eq3s', eq3s);

let sensormap = global.get('sensormap') || {};

// map of EQ3 names to ATC temp sensor topics 
// so that we can have current_temp
sensormap = {
    EQ3LPatio:'tele/tasmota_ble/LvngRoom',
    EQ3LDoor:'tele/tasmota_ble/LvngRoom',
    EQ3Dining:'tele/tasmota_ble/Dining',
    EQ3Bed1:'tele/tasmota_ble/Bedroom1',
    EQ3Bed2:'tele/tasmota_ble/Bedroom2',
    EQ3Bed3:'tele/tasmota_ble/Bedroom3',
    EQ3Bed4:'tele/tasmota_ble/Bedroom4',
    EQ3Landing:'tele/tasmota_ble/Landing',
}


global.set('sensormap', sensormap);


//let successes = Object.keys(scanner.success);

/*
11:28:42.924 MQT: stat/EQ3/001A22092CDB = 
{"cmd":"state",
"result":"ok",
"RSSI":-83,
"stattime":1613816922,
"temp":21.0,
"posn":49,
"mode":"auto",
"boost":"inactive",
"dst":"set",
"window":"closed",
"state":"unlocked",
"battery":"GOOD"}
*/

let tsplt = msg.topic.split('/');
try {
    msg.payload = JSON.parse(msg.payload);
} catch(e) {
    node.error('bad json '+msg.payload);
    return;
}

let hostdev = msg.payload.tas;
let mac = msg.payload.MAC;
let topic = msg.topic;
let DeviceName = tsplt[2];
let statname = 'RSSI'; 
let jsonname = statname;
let device_class = 'signal_strength';
let negative = false;

let tasgroup = 'tasmotas';
let cmnd_topic = 'cmnd/'+tasgroup+'/EQ3/'+DeviceName;

node.warn(mac);

if (eq3s[DeviceName]){
    eq3s[DeviceName].laststat = msg.payload;
    return;
}


let curr_temp_topic = sensormap[DeviceName];

if (!curr_temp_topic){
    curr_temp_topic = 'dummy/dummy';
}

//return;



let outs = [];

let out =
{
    
    topic: 'homeassistant/sensor/'+DeviceName+'/'+statname+'/config',
    payload:{
        device:{
            name: DeviceName,
            identifiers: [mac],
            mf: 'EQ3',
            mdl: 'EQ3',
            via_device: hostdev,
        },
        unique_id: mac+statname,
        device_class: device_class,
        //stat/EQ3/001A22092CDB
        state_topic: topic,
        name: DeviceName+'_'+statname,
        unit_of_measurement: 'dB',
        value_template: "{{ "+(negative?'-':'')+"value_json."+jsonname.split('_').join('.')+" }}",

    }
};

outs.push(JSON.parse(JSON.stringify(out)));
statname = 'setpoint'; 
jsonname = 'temp'; 
device_class = 'temperature';

out =
{
    topic: 'homeassistant/sensor/'+DeviceName+'/'+statname+'/config',
    payload:{
        device:{
            name: DeviceName,
            identifiers: [mac],
            mf: 'EQ3',
            mdl: 'EQ3',
            via_device: hostdev,
        },
        unique_id: mac+statname,
        device_class: device_class,
        //stat/EQ3/001A22092CDB
        state_topic: topic,
        name: DeviceName+'_'+statname,
        unit_of_measurement: 'C',
        value_template: "{{ "+(negative?'-':'')+"value_json."+jsonname.split('_').join('.')+" }}",
    }
};

outs.push(JSON.parse(JSON.stringify(out)));

statname = 'posn'; 
device_class = 'temperature';
jsonname = statname;

out =
{
    topic: 'homeassistant/sensor/'+DeviceName+'/'+statname+'/config',
    payload:{
        device:{
            name: DeviceName,
            identifiers: [mac],
            mf: 'EQ3',
            mdl: 'EQ3',
            via_device: hostdev,
        },
        unique_id: mac+statname,
        device_class: device_class,
        //stat/EQ3/001A22092CDB
        state_topic: topic,
        name: DeviceName+'_'+statname,
        unit_of_measurement: '%',
        value_template: "{{ "+(negative?'-':'')+"value_json."+jsonname.split('_').join('.')+" }}",
    }
};

outs.push(JSON.parse(JSON.stringify(out)));



//
// create a special entity just foe json attributes
statname = 'attr'; 
//device_class = 'temperature';
jsonname = 'mode';

out =
{
    topic: 'homeassistant/sensor/'+DeviceName+'/'+statname+'/config',
    payload:{
        device:{
            name: DeviceName,
            identifiers: [mac],
            mf: 'EQ3',
            mdl: 'EQ3',
            via_device: hostdev,
        },
        unique_id: mac+statname,
        //device_class: device_class,
        //stat/EQ3/001A22092CDB
        state_topic: topic,
        name: DeviceName+'_'+statname,
        //unit_of_measurement: '%',
        value_template: "{{ value_json."+jsonname.split('_').join('.')+" }}",

        json_attributes_topic: 'stat/EQ3/'+mac,
    }
};

outs.push(JSON.parse(JSON.stringify(out)));





statname = 'control'; 
//device_class = 'temperature';
jsonname = statname;

out =
{
    topic: 'homeassistant/climate/'+DeviceName+'/'+statname+'/config',
    payload:{
        device:{
            name: DeviceName,
            identifiers: [mac],
            mf: 'EQ3',
            mdl: 'EQ3',
            via_device: hostdev,
        },
        name: DeviceName,
        max_temp:30,
        min_temp:5,
        //aux_stat_t:msg.topic,
        //aux_stat_tpl:'{{ value_json.posn }}',
        temperature_command_topic: cmnd_topic+'/settemp',
        mode_command_topic: cmnd_topic+'/mode',
        modes: ['off','heat','auto','idle'],
        temperature_unit: 'c',
        temp_step:'0.5',
        precision:0.5,
        unique_id: mac,


        // convert valve to 'off','idle','heating'
        // valid: off, heating, cooling, drying, idle, fan
        action_topic: topic,
        action_template:"{{ 'off' if value_json.posn < 25 else 'heating' }}",
        //action_template:"{% if value_json.posn > 25 %}heating{% else %}off{% endif %}",

        // if these are present, hold is enabled
        hold_command_topic: cmnd_topic,
        hold_state_template:'{{ value_json.mode }}',
        hold_state_topic: topic,
        hold_modes: ['auto','manual','off','on','boost','unboost','lock','unlock','day','night','reqprofile 0'],
    
        
        current_temperature_topic: curr_temp_topic,
        current_temperature_template:'{{ value_json.Temperature }}',

        temperature_state_topic: topic,
        temperature_state_template:'{{ value_json.temp }}',
        
        mode_state_topic: topic,
        mode_state_template:'{{ value_json.hassmode }}',
        
        // if these are present, presets is enabled
        //away_mode_state_topic: 'stat/EQ3/'+mac,
        //away_mode_state_template:'{{ value_json.mode }}',
        //away_mode_command_topic: 'cmnd/tasmota_E89E98/EQ3/'+mac+'/mode',

        //json_attributes_topic: 'stat/EQ3/'+mac,
        //json_attributes_template:'{{ value_json.cmd | tojson }}',
        
    //    json_attributes_topic:msg.topic,
    //    json_attributes_template:
    //        '{{ {"position": value_json.posn, "window": value_json.window } | tojson }}'
        
    },
};

outs.push(JSON.parse(JSON.stringify(out)));


for (let i = 0; i < outs.length; i++){
    let newmsg = {
        topic: outs[i].topic,
        payload: JSON.stringify(outs[i].payload),
    };
    node.warn(outs[i].payload);
    node.send(newmsg);
}

eq3s[DeviceName] = eq3s[DeviceName] ||{};
eq3s[DeviceName].laststat = msg.payload;

```

**Comment by btsimonh** [comment]
hassmode generated in Tasmota:
```
    sprintf(p, ",\"hassmode\":");
    p += strlen(p);

    do {
      //0201283B042A
      // its in auto
      if ((stat & 3) == 0) { sprintf(p, "\"auto\""); break; }
      // it's set to 'OFF'
      if (((stat & 3) == 1) && (status[5] == 9)) { sprintf(p, "\"off\""); break; }
      // it's actively heating (valve open)
      if (((stat & 3) == 1) && (status[5] > 9) && (status[3] > 0)) { sprintf(p, "\"heat\""); break; }
      // it's achieved temp (valve closed)
      if (((stat & 3) == 1) && (status[5] > 9)) { sprintf(p, "\"idle\""); break; }

      sprintf(p, "\"idle\""); 
      
      break;
    } while (0);
    p += strlen(p);
```

**Comment by btsimonh** [comment]
Lovelace (edit via frontend, needs mini-climate and decluttering cards:
(note: I no longer use **base_name2** - as the above discovery message tells HA this info)
```
decluttering_templates:
  mytemplate:
    card:
      type: 'custom:mini-climate'
      entity: 'climate.[[base_name]]'
      name: '[[base_name]]'
      icon: 'mdi:radiator'
      secondary_info:
        type: fan-mode-dropdown
        icon: 'mdi:fan'
      tap_action:
        action: more-info
      hvac_mode:
        icon: 'mdi:fan'
        style: '(value, entity) => ({ color: "black" })'
        source:
          'off':
            icon: 'mdi:power'
            name: 'off'
          idle:
            icon: 'mdi:fan'
            name: idle
          heating:
            icon: 'mdi:weather-sunny'
            name: heat
          auto:
            icon: 'mdi:clock-outline'
            name: auto
      temperature:
        unit: °C
        fixed: 1
      fan_mode:
        hide: 'off'
        icon: 'mdi:fan'
        order: 0
        state:
          attribute: preset_mode
        active: '(state, entity) => true'
        source:
          state: state
          auto: auto
          manual: manual
          'off': 'off'
          'on': 'on'
          Boost: boost
          unboost: unboost
          lock: lock
          unlock: unlock
          day: day
          night: night
          reqprofile 0: reqprofile 0
        change_action: >
          (selected, state, entity) => this.call_service('climate',
          'set_preset_mode', { entity_id: entity.entity_id, preset_mode:
          selected })
      indicators:
        valve:
          icon:
            template: '() => "mdi:valve"'
            style: |
              (value) => (value > 80 ? { color: 'red'} 
                : value > 40 ? { color: 'orange'}
                : value > 0 ? { color: 'gold'}
                : { color: 'green' })
          unit: '%'
          round: 1
          source:
            entity: 'sensor.[[base_name]]_posn'
        humidity:
          icon:
            template: '() => "mdi:water"'
            style: |
              (value) => (value > 80 ? { color: 'darkblue'} 
                : value > 50 ? { color: 'blue'}
                : value > 40 ? { color: 'lightblue'}
                : { color: 'grey' })
          unit: '%'
          round: 0
          source:
            entity: 'sensor.[[base_name2]]_humidity'
        preset_mode:
          icon: 'mdi:approximately-equal'
          state:
            attribute: preset_mode
views:
  - path: default_view
    title: Home
    cards:
      - type: 'custom:decluttering-card'
        template: mytemplate
        variables:
          - base_name: eq3bed1
          - base_name2: bedroom1
```
